import { Suspense } from "react";
import ContactListsClient from "@/components/dashboard/contact-lists/ContactListsClient";
import api from "@/app/api/api"; // 🔌 Import your configured axios instance

/**
 * 🎯 Server Component for Contact Lists Page
 */

// Mock data - Replace with API call when backend is ready
const MOCK_CONTACTS = [
  {
    id: 1,
    name: "Shaima Al Suwaidi",
    gender: "Female",
    address: "Dubai culture and art authority",
    phones: ["+971501014411"],
    landlines: [""],
    email: "shaima.alsuwaidi@dubaiculture.ae",
    top_customer: "No",
    decision_maker_status: "Yes",
    status: "New Lead",
    employee: "Sedra Quraid",
    country: "United Arab Emirates",
    company: "Dubai Culture & Arts Authority",
    budget: "5000",
    avg_stands_year: "2024",
    avg_events_year: "2025",
    company_website_url: "https://example.com",
    social_links: [""],
    job_title: "CEO",
    notes: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam, quod.",
    created_at: "2026-01-20"
  },
  {
    id: 2,
    name: "maitha al blooshi",
    gender: "Female",
    address: "Dubai culture and art authority",
    phones: ["+971508879993", "+971508879993"],
    landlines: [""],
    email: "alblooshi@dubaiculture.gov.ae",
    top_customer: "No",
    decision_maker_status: "No",
    status: "New Lead",
    employee: "Sedra Quraid",
    country: "United Arab Emirates",
    company: "Dubai Culture & Arts Authority",
    budget: "10000",
    avg_stands_year: "2024",
    avg_events_year: "2025",
    company_website_url: "https://example.com",
    social_links: [""],
    job_title: "event manager",
    notes: "she is responsible for Al Marmoom film festival...",
    created_at: "2026-01-20"
  },
  {
    id: 3,
    name: "Fakhry Al sarraj",
    gender: "Male",
    address: "DCT Abu Dhabi",
    phones: ["0505962404"],
    landlines: [""],
    email: "falsarraj@dctabudhabi.ae",
    top_customer: "Yes",
    decision_maker_status: "Yes",
    status: "1st Contact Done",
    employee: "Sedra Quraid",
    country: "United Arab Emirates",
    company: "Department of Culture and Tourism",
    budget: "15000",
    avg_stands_year: "2024",
    avg_events_year: "2025",
    company_website_url: "https://example.com",
    social_links: [""],
    job_title: "Director",
    notes: "Email sent with company profile...",
    created_at: "2026-01-19"
  },
  {
    id: 4,
    name: "John Smith",
    gender: "Male",
    address: "One Sheikh Zayed Road",
    phones: ["+97141234567"],
    landlines: [""],
    email: "john.smith@techcorp.com",
    top_customer: "Yes",
    decision_maker_status: "Yes",
    status: "Meeting Scheduled",
    employee: "Ahmed Hassan",
    country: "United Arab Emirates",
    company: "TechCorp Solutions",
    budget: "25000",
    avg_stands_year: "2-3",
    avg_events_year: "5",
    company_website_url: "https://techcorp.com",
    social_links: [""],
    job_title: "Marketing Manager",
    notes: "Interested in the digital transformation package.",
    created_at: "2026-02-01"
  },
  {
    id: 5,
    name: "Sarah Lee",
    gender: "Female",
    address: "Main Street, London",
    phones: ["+442071234567"],
    landlines: [""],
    email: "s.lee@globalmedia.uk",
    top_customer: "No",
    decision_maker_status: "No",
    status: "Follow - Up",
    employee: "Sedra Quraid",
    country: "United Kingdom",
    company: "Global Media Group",
    budget: "8500",
    avg_stands_year: "1",
    avg_events_year: "2",
    company_website_url: "https://globalmedia.uk",
    social_links: [""],
    job_title: "Event Coordinator",
    notes: "Requires a quote for the summer expo.",
    created_at: "2026-02-02"
  },
  {
    id: 6,
    name: "Mohammed Ibrahim",
    gender: "Male",
    address: "Riyadh Digital City",
    phones: ["+966112233445"],
    landlines: [""],
    email: "m.ibrahim@sauditech.sa",
    top_customer: "Yes",
    decision_maker_status: "Yes",
    status: "Proposal Submitted",
    employee: "Ahmed Hassan",
    country: "Saudi Arabia",
    company: "Saudi Tech Ventures",
    budget: "45000",
    avg_stands_year: "4",
    avg_events_year: "10",
    company_website_url: "https://sauditech.sa",
    social_links: [""],
    job_title: "Operational Director",
    notes: "Reviewing the proposal. High potential lead.",
    created_at: "2026-01-25"
  },
  {
    id: 7,
    name: "Emma Wilson",
    gender: "Female",
    address: "Silicon Valley, CA",
    phones: ["+14155550199"],
    landlines: [""],
    email: "emma.wilson@cloudsoft.com",
    top_customer: "No",
    decision_maker_status: "Yes",
    status: "New Lead",
    employee: "Sedra Quraid",
    country: "USA",
    company: "CloudSoft Inc.",
    budget: "12000",
    avg_stands_year: "2",
    avg_events_year: "4",
    company_website_url: "https://cloudsoft.com",
    social_links: [""],
    job_title: "CTO",
    notes: "Cold call response was positive.",
    created_at: "2026-02-03"
  },
  {
    id: 8,
    name: "Karl Heinz",
    gender: "Male",
    address: "Berliner Strasse 10",
    phones: ["+442071234567"],
    landlines: [""],
    email: "k.heinz@autowerke.de",
    top_customer: "Yes",
    decision_maker_status: "Yes",
    status: "Brief Received",
    employee: "Ahmed Hassan",
    country: "Germany",
    company: "AutoWerke Deutschland",
    budget: "60000",
    avg_stands_year: "6",
    avg_events_year: "15",
    company_website_url: "https://autowerke.de",
    social_links: [""],
    job_title: "Head of Marketing",
    notes: "Large international presence. Looking for long-term partner.",
    created_at: "2026-01-15"
  },
  {
    id: 9,
    name: "Layla Rashid",
    gender: "Female",
    address: "Muscat Hills",
    phones: ["+96824123456"],
    landlines: [""],
    email: "l.rashid@omanenergy.om",
    top_customer: "No",
    decision_maker_status: "No",
    status: "Comments Received",
    employee: "Sedra Quraid",
    country: "Oman",
    company: "Oman Energy TB",
    budget: "7000",
    avg_stands_year: "1",
    avg_events_year: "3",
    company_website_url: "https://omanenergy.om",
    social_links: [""],
    job_title: "Procurement Manager",
    notes: "Feedback received on the initial draft.",
    created_at: "2026-01-28"
  },
  {
    id: 10,
    name: "Yuki Tanaka",
    gender: "Male",
    address: "Shinjuku-ku, Tokyo",
    phones: ["+81312345678"],
    landlines: [""],
    email: "y.tanaka@japanrobotics.jp",
    top_customer: "Yes",
    decision_maker_status: "Yes",
    status: "Quotation Submitted",
    employee: "Ahmed Hassan",
    country: "Japan",
    company: "Japan Robotics Group",
    budget: "35000",
    avg_stands_year: "3",
    avg_events_year: "8",
    company_website_url: "https://japanrobotics.jp",
    social_links: [""],
    job_title: "VP of Sales",
    notes: "Detailed quotation sent for three upcoming exhibitions.",
    created_at: "2026-01-10"
  },
  {
    id: 11,
    name: "Alice Brown",
    gender: "Female",
    address: "Sydney Harbour",
    phones: ["+61298765432"],
    landlines: [""],
    email: "alice.b@ozevents.au",
    top_customer: "No",
    decision_maker_status: "Yes",
    status: "Project Won",
    employee: "Sedra Quraid",
    country: "Australia",
    company: "OzEvents Ltd",
    budget: "18000",
    avg_stands_year: "5",
    avg_events_year: "12",
    company_website_url: "https://ozevents.au",
    social_links: [""],
    job_title: "Founder",
    notes: "Contract signed! Start execution next month.",
    created_at: "2025-12-20"
  },
  {
    id: 12,
    name: "Jean Dupont",
    gender: "Male",
    address: "Champs-Élysées, Paris",
    phones: ["+33123456789"],
    landlines: [""],
    email: "j.dupont@luxurystyle.fr",
    top_customer: true,
    decision_maker_status: "Yes",
    status: "Project Lost",
    employee: "Ahmed Hassan",
    country: "France",
    company: "Luxury Style Paris",
    budget: "22000",
    avg_stands_year: "2",
    avg_events_year: "6",
    company_website_url: "https://luxurystyle.fr",
    social_links: [""],
    job_title: "Brand Ambassador",
    notes: "Went with a local competitor for the Paris Fashion Week.",
    created_at: "2026-01-05"
  },
  {
    id: 13,
    name: "Chen Wei",
    gender: "Male",
    address: "Pudong, Shanghai",
    phones: ["+862112345678"],
    landlines: [""],
    email: "chen.wei@chinamanufacturing.cn",
    top_customer: "No",
    decision_maker_status: "No",
    status: "Revising Quotation",
    employee: "Sedra Quraid",
    country: "China",
    company: "China Manufacturing Co.",
    budget: "9500",
    avg_stands_year: "10+",
    avg_events_year: "20+",
    company_website_url: "https://chinamanufacturing.cn",
    social_links: [""],
    job_title: "Export Manager",
    notes: "Adjusting budget constraints as per request.",
    created_at: "2026-02-04"
  },
  {
    id: 14,
    name: "Elena Rossi",
    gender: "Female",
    address: "Via Montenapoleone, Milan",
    phones: ["+39023456789"],
    landlines: [""],
    email: "e.rossi@italianfashion.it",
    top_customer: true,
    decision_maker_status: "Yes",
    status: "Final Proposal & Quotation Submitted",
    employee: "Ahmed Hassan",
    country: "Italy",
    company: "Italian Fashion Week",
    budget: "55000",
    avg_stands_year: "4",
    avg_events_year: "8",
    company_website_url: "https://italianfashion.it",
    social_links: [""],
    job_title: "Executive Producer",
    notes: "Final stage of negotiations.",
    created_at: "2026-01-30"
  },
  {
    id: 15,
    name: "Nour Al Amri",
    gender: "Female",
    address: "West Bay, Doha",
    phones: ["+97444123456"],
    landlines: [""],
    email: "n.alamri@qatarholding.qa",
    top_customer: "No",
    decision_maker_status: "Yes",
    status: "2nd Contact Done",
    employee: "Sedra Quraid",
    country: "Qatar",
    company: "Qatar Holding Group",
    budget: "13500",
    avg_stands_year: "3",
    avg_events_year: "5",
    company_website_url: "https://qatarholding.qa",
    social_links: [""],
    job_title: "Investment Analyst",
    notes: "Follow up scheduled for next week.",
    created_at: "2026-02-04"
  }
];

export default function ContactListsPage() {
  return (
    <Suspense fallback={<div className="d-none">Loading contacts...</div>}>
      <ContactListsClient initialContacts={MOCK_CONTACTS} />
    </Suspense>
  );
}
